version: '3'

volumes:
  database: {}

services:
  mysql:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - '3306'
    volumes:
      - database:/var/lib/mysql
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
  app:
    image: ar-import
    build: .
    links:
      - mysql
      - postgresql
    environment:
      DATABASE_URL: mysql2://root:password@db/db
    volumes:
      - .:/app/
